### ISSUE TITLE
Instructions for OpenShift are out dated now

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-cloud-openshift#9]
- Starter tier doesn't seem to exist now
- Users have to sign up for a 30-day trial and register with a working payment method

**Comment by yeekangc** [comment]
@MaiHameed @gkwan-ibm, are we looking at this?

**Comment by MaiHameed** [comment]
Looked into it, one of the links we sent the users to now points to a dead link. It seems that the explanations for the different plans refer to the 30-day trial as the starter tier:
![image](https://user-images.githubusercontent.com/26514093/63272729-9b56f500-c26a-11e9-90db-d113e89dcedb.png)

But when going to select a plan, it doesn't mention the starter tier, and just provides an option for a 30-day trial, I decided to link to the page shown here:
![image](https://user-images.githubusercontent.com/26514093/63272782-b45fa600-c26a-11e9-870e-300008aa7b32.png) 

Also decided to reword the sentence to call it a trial instead of the starter tier.

**Comment by MaiHameed** [comment]
Addressed feedback is now live, closing.
